### ISSUE TITLE
Use Harmony 2.2.2 instead of 2.3.3

### ISSUE THREAD

**Issue by Mimonsi** [rodrigmatrix/StationEntranceVisuals#2]
Due to known issues with Harmony Versions 2.3.+ ([reference: Conversation with T.D.W. and krzychu124 on Discord](https://discord.com/channels/1024242828114673724/1222219069021884527/1314539451422085161)) I would advise you to change your version to 2.2.2 instead. I found out about this while testing a version of the Mod Zone Organizer I'm working on.

**Comment by rodrigmatrix** [comment]
Thanks Konsi. Issue was fixed with the new update
